# Generated by Django 5.2.11 on 2026-02-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_portfolioitemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ООО «Немново Тур»', max_length=200, verbose_name='Название')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('office_address', models.TextField(blank=True, verbose_name='Адрес офиса')),
                ('unp', models.CharField(blank=True, max_length=20, verbose_name='УНП')),
                ('okpo', models.CharField(blank=True, max_length=30, verbose_name='ОКПО')),
                ('trade_register', models.CharField(blank=True, max_length=200, verbose_name='Регистрация в торговом реестре')),
                ('services_register', models.CharField(blank=True, max_length=200, verbose_name='Регистрация в реестре бытовых услуг')),
                ('contact_email', models.EmailField(blank=True, default='office@nemnovotour.by', max_length=254, verbose_name='Email для контакта')),
            ],
            options={
                'verbose_name': 'Реквизиты компании',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Список URL дополнительных фото (устаревшее — используйте «Фото» ниже)'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='long_desc',
            field=models.TextField(help_text='Блоки: строка-заголовок (без буллета), ниже строки с «• » — пункты списка. Новая строка без «• » начинает следующий блок.'),
        ),
    ]
