# Generated by Django 5.2.11 on 2026-02-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_add_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-is_pinned', 'order', '-event_date', 'id'], 'verbose_name': 'Элемент портфолио', 'verbose_name_plural': 'Элементы портфолио'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
