# Generated by Django 5.2.11 on 2026-03-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarbooking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
