# Generated by Django 4.2.28 on 2026-03-04 08:37

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_alter_calendarbooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floattriptranslation',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
    ]
