# Generated by Django 4.2.28 on 2026-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_float_description_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floattrip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='floats/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='floattrip',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL изображения (если нет загрузки)'),
        ),
        migrations.AddField(
            model_name='floattriptranslation',
            name='short_desc',
            field=models.TextField(blank=True, verbose_name='Краткое описание (для карточки)'),
        ),
    ]
