# Generated by Django 4.2.28 on 2026-03-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_float_trip_image_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floattriptranslation',
            name='short_desc',
        ),
    ]
