# Generated by Django 4.2.28 on 2026-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_remove_float_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='floattrip',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на YouTube (youtube.com/watch?v=... или youtube.com/embed/...), Vimeo (vimeo.com/...) или прямой URL видео (.mp4)', verbose_name='Видео'),
        ),
    ]
