# Generated by Django 4.2.28 on 2026-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_float_trip_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='floattrip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
