# Generated by Django 4.2.28 on 2026-03-11 07:31

from django.db import migrations, models


def fill_bank_details(apps, schema_editor):
    CompanyInfo = apps.get_model('content', 'CompanyInfo')
    CompanyInfo.objects.filter(bank_account='', bank_institution='').update(
        bank_account='BY20 MTBK 3012 0001 0933 0012 6296',
        bank_institution='в ЗАО «МТБанк», БИК MTBKBY22',
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_service_float_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Расчётный счёт', max_length=50, verbose_name='р/с'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bank_institution',
            field=models.CharField(blank=True, help_text='Напр.: в ЗАО «МТБанк», БИК MTBKBY22', max_length=200, verbose_name='Банк'),
        ),
        migrations.RunPython(fill_bank_details, noop),
    ]
