# Generated by Django 4.2.28 on 2026-03-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_companyinfo_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='float_trip',
            field=models.ForeignKey(blank=True, help_text='Если выбрано — название, описание и фото берутся из сплава', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='content.floattrip', verbose_name='Сплав'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='time',
            field=models.TimeField(blank=True, help_text='Напр. 9:30, 11:00', null=True, verbose_name='Время (опц.)'),
        ),
    ]
