# Generated by Django 4.2.28 on 2026-03-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_calendarevent_float_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['date', 'time', 'order', 'id'], 'verbose_name': 'Событие в календаре', 'verbose_name_plural': 'События в календаре'},
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='page_key',
            field=models.CharField(choices=[('privacy', 'Политика обработки персональных данных'), ('cookie-policy', 'Политика в отношении обработки cookie'), ('payment', 'Оплата')], max_length=50, unique=True, verbose_name='Идентификатор'),
        ),
    ]
