# Generated by Django 4.2.28 on 2026-03-11 08:03

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_ensure_legal_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalpage',
            options={'verbose_name': 'Информационная страница', 'verbose_name_plural': 'Информационные страницы'},
        ),
        migrations.AlterField(
            model_name='legalpagetranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Можно вставлять картинки через кнопку «Изображение» в редакторе.', verbose_name='Содержание'),
        ),
    ]
