# Generated by Django 4.2.28 on 2026-03-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_legalpage_content_ckeditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
                'verbose_name_plural': 'Страница «О нас»',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'Блок «О нас» (главная)', 'verbose_name_plural': 'Блок «О нас» (главная)'},
        ),
        migrations.CreateModel(
            name='AboutPageContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('ru', 'Русский'), ('be', 'Беларуская'), ('en', 'English'), ('pl', 'Polski'), ('zh', '中文')], max_length=5)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('paragraphs', models.TextField(blank=True, help_text='Абзацы разделяются пустой строкой (\\n\\n).', verbose_name='Текст (абзацы)')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.aboutpagecontent')),
            ],
            options={
                'verbose_name': 'Перевод страницы «О нас»',
                'verbose_name_plural': 'Переводы страницы «О нас»',
                'ordering': ['about_page', 'locale'],
                'unique_together': {('about_page', 'locale')},
            },
        ),
    ]
