# Generated by Django 4.2.28 on 2026-03-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_about_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Если выбрано — название и описание берутся из услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='content.service', verbose_name='Услуга'),
        ),
    ]
