# Generated by Django 4.2.28

from django.db import migrations, models


def ensure_public_offer_page(apps, schema_editor):
    LegalPage = apps.get_model('content', 'LegalPage')
    LegalPageTranslation = apps.get_model('content', 'LegalPageTranslation')

    page, created = LegalPage.objects.get_or_create(
        page_key='public-offer',
        defaults={},
    )
    if created:
        LegalPageTranslation.objects.get_or_create(
            page=page,
            locale='ru',
            defaults={
                'title': 'Договор публичной оферты',
                'content': 'Содержание договора публичной оферты будет добавлено в разделе администратора.',
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_calendar_event_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='page_key',
            field=models.CharField(
                choices=[
                    ('privacy', 'Политика обработки персональных данных'),
                    ('cookie-policy', 'Политика в отношении обработки cookie'),
                    ('payment', 'Оплата'),
                    ('public-offer', 'Договор публичной оферты'),
                ],
                max_length=50,
                unique=True,
                verbose_name='Идентификатор',
            ),
        ),
        migrations.RunPython(ensure_public_offer_page, noop),
    ]
