# Generated by Django 4.2.28 on 2026-03-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_legalpage_public_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Оставьте пустым для корневого раздела (Велопрогулки, Экскурсии и т.д.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.service', verbose_name='Родительский раздел'),
        ),
    ]
