# Generated by Django 5.2.11 on 2026-03-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0058_create_certificate_content'),
        ('content', '0058_legalpage_agencies'),
    ]

    operations = [
    ]
