from django.urls import path
from . import views

urlpatterns = [
    path('hero', views.hero_content),
    path('hero/', views.hero_content),
    path('about-content', views.about_content),
    path('about-content/', views.about_content),
    path('legal/<str:page_key>/', views.legal_page),
    path('company-info', views.company_info),
    path('company-info/', views.company_info),
    path('contact', views.contact_submit),
    path('contact/', views.contact_submit),
    path('partners', views.partner_list),
    path('partners/', views.partner_list),
    path('services', views.service_list),
    path('services/', views.service_list),
    path('services/<slug:slug>/', views.service_detail),
    path('news', views.news_list),
    path('news/', views.news_list),
    path('news/<slug:slug>/', views.news_detail),
    path('promos', views.promo_list),
    path('promos/', views.promo_list),
    path('promos/<slug:slug>/', views.promo_detail),
    path('hot-offers', views.hot_offer_list),
    path('hot-offers/', views.hot_offer_list),
    path('portfolio', views.portfolio_list),
    path('portfolio/', views.portfolio_list),
    path('portfolio/<slug:slug>/', views.portfolio_detail),
    path('portfolio/<slug:slug>/download/', views.portfolio_download),
    path('reviews', views.review_list),
    path('reviews/', views.review_list),
    path('calendar-events', views.calendar_events_list),
    path('calendar-events/', views.calendar_events_list),
    path('calendar-events/<int:pk>', views.calendar_event_detail),
    path('calendar-events/<int:pk>/', views.calendar_event_detail),
    path('calendar-events/<int:pk>/book/', views.calendar_event_book),
    path('float-trips', views.float_trip_list),
    path('float-trips/', views.float_trip_list),
    path('float-trips/<slug:slug>', views.float_trip_detail),
    path('float-trips/<slug:slug>/', views.float_trip_detail),
]
